"""empty message

Revision ID: 244a239775d5
Revises: 52367fd14617
Create Date: 2022-03-21 14:58:28.526314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244a239775d5'
down_revision = '52367fd14617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'price')
    # ### end Alembic commands ###
