"""empty message

Revision ID: 52367fd14617
Revises: 85d9735cd88e
Create Date: 2022-03-21 14:35:22.927827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52367fd14617'
down_revision = '85d9735cd88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'location')
    # ### end Alembic commands ###
